apiVersion: v1
kind: Service
metadata:
    name: nginx-service
spec:
    selector:
        app: nginx-app # deployment.yml의 pod와 매칭
    type: NodePort
    ports:
        - port: 80 # Service의 포트
          targetPort: 80 # Container의 내부 포트
          nodePort: 30080 # External 포트 (외부접근)
