services:
    gateway:
        build:
            context: .
            dockerfile: ./apps/gateway/Dockerfile
            target: development
        command: npm run start:dev gateway
        ports:
            - '3000:3000'
        volumes:
            - .:/usr/src/app
            - /usr/src/app/node_modules
        env_file:
            - ./apps/gateway/.env
    user:
        build:
            context: .
            dockerfile: ./apps/user/Dockerfile
            target: development
        command: npm run start:dev user
        depends_on:
            mysql:
                condition: service_healthy
        # ports:
        #     - '3001:3000'
        volumes:
            - .:/usr/src/app
            - /usr/src/app/node_modules
        env_file:
            - ./apps/user/.env

    product:
        build:
            context: .
            dockerfile: ./apps/product/Dockerfile
            target: development
        command: npm run start:dev product
        depends_on:
            mysql:
                condition: service_healthy
        # ports:
        #     - '3002:3000'
        volumes:
            - .:/usr/src/app
            - /usr/src/app/node_modules
        env_file:
            - ./apps/product/.env
    order:
        build:
            context: .
            dockerfile: ./apps/order/Dockerfile
            target: development
        command: npm run start:dev order
        depends_on:
            mongo_order:
                condition: service_healthy
        # ports:
        #     - '3003:3000'
        volumes:
            - .:/usr/src/app
            - /usr/src/app/node_modules
        env_file:
            - ./apps/order/.env
    mongo_order:
        image: mongo:8
        environment:
            MONGO_INITDB_ROOT_USERNAME: mongo
            MONGO_INITDB_ROOT_PASSWORD: pass1234
        ports:
            - '6003:27017'
        volumes:
            # - ./mongo/order:/data/lib
            - ./mongo/order:/data/db
        command: mongod --quiet --logpath /dev/null
        healthcheck:
            test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
            interval: 5s
            timeout: 5s
            retries: 10
            start_period: 5s
    payment-command:
        build:
            context: .
            dockerfile: ./apps/payment-command/Dockerfile
            target: development
        command: npm run start:dev payment-command
        depends_on:
            mongo_payment-command:
                condition: service_healthy
        # ports:
        #     - '3004:3000'
        volumes:
            - .:/usr/src/app
            - /usr/src/app/node_modules
        env_file:
            - ./apps/payment-command/.env
    payment-query:
        build:
            context: .
            dockerfile: ./apps/payment-query/Dockerfile
            target: development
        command: npm run start:dev payment-query
        depends_on:
            mongo_payment-query:
                condition: service_healthy
        # ports:
        #     - '3004:3000'
        volumes:
            - .:/usr/src/app
            - /usr/src/app/node_modules
        env_file:
            - ./apps/payment-query/.env
    mongo_payment-command:
        image: mongo:8
        environment:
            MONGO_INITDB_ROOT_USERNAME: mongo
            MONGO_INITDB_ROOT_PASSWORD: pass1234
        ports:
            - '6010:27017'
        volumes:
            - ./mongo/payment-command:/data/db
        command: mongod --quiet --logpath /dev/null
        healthcheck:
            test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
            interval: 5s
            timeout: 5s
            retries: 10
            start_period: 5s
    mongo_payment-query:
        image: mongo:8
        environment:
            MONGO_INITDB_ROOT_USERNAME: mongo
            MONGO_INITDB_ROOT_PASSWORD: pass1234
        ports:
            - '6011:27017'
        volumes:
            - ./mongo/payment-query:/data/db
        command: mongod --quiet --logpath /dev/null
        healthcheck:
            test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
            interval: 5s
            timeout: 5s
            retries: 10
            start_period: 5s
    notification:
        build:
            context: .
            dockerfile: ./apps/notification/Dockerfile
            target: development
        command: npm run start:dev notification
        depends_on:
            mysql:
                condition: service_healthy
        # ports:
        #     - '3005:3000'
        volumes:
            - .:/usr/src/app
            - /usr/src/app/node_modules
        env_file:
            - ./apps/notification/.env
    mysql:
        image: mysql:5.7
        platform: linux/amd64
        ports:
            - '6666:3306'
        volumes:
            - ./mysql/data:/var/lib/mysql
            - ./mysql/my.cnf:/etc/mysql/my.cnf
        healthcheck:
            test:
                [
                    'CMD',
                    'mysqladmin',
                    'ping',
                    '-h',
                    'localhost',
                    '-u',
                    'root',
                    '-proot',
                ]
            interval: 5s
            timeout: 5s
            retries: 10
            start_period: 5s
        environment:
            TZ: Asia/Seoul
            # MYSQL_USER: root
            MYSQL_PASSWORD: 'pass1234'
            MYSQL_DATABASE: msa
            MYSQL_ROOT_PASSWORD: 'pass1234'
    zookeeper:
        image: confluentinc/cp-zookeeper:latest
        environment:
            ZOOKEEPER_CLIENT_PORT: 2181
            ZOOKEEPER_TICK_TIME: 2000
        ports:
            - 2181:2181
    kafka:
        image: confluentinc/cp-kafka:latest
        depends_on:
            - zookeeper
        ports:
            - 9092:9092
            - 29092:29092
        environment:
            KAFKA_BROKER_ID: 1
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
            KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
