services:
    gateway:
        image: devonyou/gateway:latest
        ports:
            - '3000:3000'
        env_file:
            - ./apps/gateway/.env

    user:
        image: devonyou/user:latest
        ports:
            - '3001:3000'
        expose:
            - '3000'
            - '3010'
        env_file:
            - ./apps/user/.env

    product:
        image: devonyou/product:latest
        expose:
            - '3010'
        env_file:
            - ./apps/product/.env

    order:
        image: devonyou/order:latest
        expose:
            - '3010'
        env_file:
            - ./apps/order/.env

    payment:
        image: devonyou/payment:latest
        expose:
            - '3010'
        env_file:
            - ./apps/payment/.env

    notification:
        image: devonyou/notification:latest
        expose:
            - '3010'
        env_file:
            - ./apps/notification/.env

    mysql:
        image: mysql:8.4
        platform: linux/amd64
        ports:
            - '3306:3306'
        volumes:
            - ./mysql/data:/var/lib/mysql
            - ./mysql/my.cnf:/etc/mysql/my.cnf
        healthcheck:
            test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost', '-u', 'root', '-ppass1234']
            interval: 5s
            timeout: 5s
            retries: 10
            start_period: 5s
        environment:
            TZ: Asia/Seoul
            MYSQL_ROOT_PASSWORD: pass1234

    redis:
        image: redis:7-alpine
        ports:
            - '6379:6379'
        volumes:
            - ./redis/data:/data
        restart: always
        command: redis-server --appendonly yes --requirepass pass1234
        healthcheck:
            test: ['CMD', 'redis-cli', '-a', 'pass1234', 'ping']
            interval: 5s
            timeout: 3s
            retries: 5

    redis-insight:
        image: redis/redisinsight:latest
        restart: always
        ports:
            - 5540:5540
        volumes:
            - ./redis-insight:/db
        healthcheck:
            test: ['CMD', 'curl', '-f', 'http://localhost:5540']
            interval: 5s
            timeout: 3s
            retries: 5
        depends_on:
            redis:
                condition: service_healthy

    rabbitmq:
        image: rabbitmq:3-management-alpine
        ports:
            - '5672:5672'
            - '15672:15672'
        environment:
            - RABBITMQ_DEFAULT_USER=admin
            - RABBITMQ_DEFAULT_PASS=pass1234
        volumes:
            - ./rabbitmq/data:/var/lib/rabbitmq
        healthcheck:
            # test: ['CMD', 'rabbitmq-diagnostics', 'check_port_connectivity']
            # test: ['CMD', 'rabbitmqctl', 'status']
            interval: 5s
            timeout: 3s
            retries: 5
        restart: unless-stopped
