apiVersion: v1
kind: Service
metadata:
  labels:
    app: user
  name: {{ .Chart.Name }}-user-cluster-ip
spec:
  type: ClusterIP
  ports:
    - name: grpc
      port: 3010
      protocol: TCP
      targetPort: 3010
    - name: http
      port: 3000
      protocol: TCP
      targetPort: 3000
  selector:
    app: user
