apiVersion: apps/v1

kind: Deployment

metadata:
    name: {{ .Chart.Name }}-user-deployment
    labels:
        app: user

spec:
    replicas: {{ .Values.user.replicas }}
    selector:
        matchLabels:
            app: user
    strategy:
        type: RollingUpdate
        rollingUpdate:
            maxSurge: 1
            maxUnavailable: 1
    template:
        metadata:
            labels:
                app: user
        spec:
            containers:
                - image: devonyou/user:latest
                  name: user
                  envFrom:
                    - configMapRef:
                        name: user-config-map
                    - secretRef:
                        name: user-secret
                  ports:
                    - containerPort: 3010
                    - containerPort: 3000
                  livenessProbe:
                    tcpSocket:
                      port: 3010
                    periodSeconds: 10
                  readinessProbe:
                    tcpSocket:
                      port: 3010
                    periodSeconds: 10
