apiVersion: v1
kind: Secret
metadata:
    name: user-secret
data:
    GOOGLE_CLIENT_ID: {{ .Values.user.google_client_id | b64enc }}
    GOOGLE_CLIENT_SECRET: {{ .Values.user.google_client_secret | b64enc }}
    GOOGLE_AUTH_CALLBACK_URL: {{ .Values.user.google_auth_callback_url | b64enc }}
    JWT_ACCESS_SECRET_KEY: {{ .Values.user.jwt_access_secret_key | b64enc }}
    JWT_ACCESS_EXPIRATION_TIME: {{ .Values.user.jwt_access_expiration_time | b64enc }}
    JWT_REFRESH_SECRET_KEY: {{ .Values.user.jwt_refresh_secret_key | b64enc }}
    JWT_REFRESH_EXPIRATION_TIME: {{ .Values.user.jwt_refresh_expiration_time | b64enc }}
    MYSQL_URL: {{ .Values.user.mysql_url | b64enc }}
    REDIS_URL: {{ .Values.user.redis_url | b64enc }}
