// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.5
//   protoc               v5.29.3
// source: proto/order.proto

/* eslint-disable */
import type { Metadata } from "@grpc/grpc-js";
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "order";

export enum OrderStatus {
  PAYMENT_PENDING = 0,
  PAYMENT_SUCCESS = 1,
  PAYMENT_FAILED = 2,
  PAYMENT_CANCELED = 3,
  SHIPPED = 4,
  UNRECOGNIZED = -1,
}

export interface Order {
  id: string;
  userId: number;
  amount: number;
  status: OrderStatus;
  orderItems: OrderItem[];
  delivery: DeliveryResponse | undefined;
  paymentId: number;
}

export interface OrderItem {
  id: number;
  productId: number;
  productName: string;
  quantity: number;
  price: number;
}

export interface Delivery {
  id: number;
  orderId: string;
  postCode: string;
  street: string;
}

/** response */
export interface OrderResponse {
  id: string;
  userId: number;
  amount: number;
  status: OrderStatus;
  orderItems: OrderItemResponse[];
  delivery: DeliveryResponse | undefined;
  paymentId: number;
  createdAt: string;
  updatedAt: string;
}

export interface OrderListResponse {
  orders: OrderResponse[];
}

export interface OrderItemResponse {
  id: number;
  productId: number;
  productName: string;
  quantity: number;
  price: number;
}

export interface DeliveryResponse {
  id: number;
  orderId: string;
  postCode: string;
  street: string;
}

/** initiate order */
export interface InitiateOrderRequest {
  userId: number;
  items: OrderItemRequest[];
  delivery: DeliveryRequest | undefined;
}

export interface OrderItemRequest {
  productId: number;
  quantity: number;
}

export interface DeliveryRequest {
  postCode: string;
  street: string;
}

/** complete order */
export interface CompleteOrderRequest {
  userId: number;
  orderId: string;
  providerPaymentId: string;
}

export interface CancelOrderRequest {
  orderId: string;
}

export interface GetOrderByIdAndUserRequest {
  orderId: string;
  userId: number;
}

export interface GetOrdersByUserIdRequest {
  userId: number;
}

export const ORDER_PACKAGE_NAME = "order";

export interface OrderServiceClient {
  initiateOrder(request: InitiateOrderRequest, metadata?: Metadata): Observable<OrderResponse>;

  completeOrder(request: CompleteOrderRequest, metadata?: Metadata): Observable<OrderResponse>;

  cancelOrder(request: CancelOrderRequest, metadata?: Metadata): Observable<OrderResponse>;

  getOrderByIdAndUser(request: GetOrderByIdAndUserRequest, metadata?: Metadata): Observable<OrderResponse>;

  getOrdersByUserId(request: GetOrdersByUserIdRequest, metadata?: Metadata): Observable<OrderListResponse>;
}

export interface OrderServiceController {
  initiateOrder(
    request: InitiateOrderRequest,
    metadata?: Metadata,
  ): Promise<OrderResponse> | Observable<OrderResponse> | OrderResponse;

  completeOrder(
    request: CompleteOrderRequest,
    metadata?: Metadata,
  ): Promise<OrderResponse> | Observable<OrderResponse> | OrderResponse;

  cancelOrder(
    request: CancelOrderRequest,
    metadata?: Metadata,
  ): Promise<OrderResponse> | Observable<OrderResponse> | OrderResponse;

  getOrderByIdAndUser(
    request: GetOrderByIdAndUserRequest,
    metadata?: Metadata,
  ): Promise<OrderResponse> | Observable<OrderResponse> | OrderResponse;

  getOrdersByUserId(
    request: GetOrdersByUserIdRequest,
    metadata?: Metadata,
  ): Promise<OrderListResponse> | Observable<OrderListResponse> | OrderListResponse;
}

export function OrderServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = [
      "initiateOrder",
      "completeOrder",
      "cancelOrder",
      "getOrderByIdAndUser",
      "getOrdersByUserId",
    ];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("OrderService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("OrderService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const ORDER_SERVICE_NAME = "OrderService";
