// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.5
//   protoc               v5.29.3
// source: proto/order.proto

/* eslint-disable */
import type { Metadata } from "@grpc/grpc-js";
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "order";

export enum OrderStatus {
  CREATED = 0,
  STOCK_RESERVED = 1,
  PAYMENT_PENDING = 2,
  PAYMENT_SUCCESS = 3,
  PAYMENT_FAILED = 4,
  CANCELED = 5,
  SHIPPED = 6,
  COMPLETED = 7,
  UNRECOGNIZED = -1,
}

export interface Order {
  id: string;
  userId: number;
  amount: number;
  status: OrderStatus;
  orderItems: OrderItem[];
  delivery: DeliveryResponse | undefined;
  paymentId: string;
}

export interface OrderItem {
  id: number;
  productId: number;
  productName: string;
  quantity: number;
  price: number;
}

export interface Delivery {
  id: number;
  orderId: string;
  postCode: string;
  street: string;
}

/** response */
export interface OrderResponse {
  id: string;
  userId: number;
  amount: number;
  status: OrderStatus;
  orderItems: OrderItemResponse[];
  delivery: DeliveryResponse | undefined;
  paymentId: string;
  createdAt: string;
  updatedAt: string;
}

export interface OrderListResponse {
  orders: OrderResponse[];
}

export interface OrderItemResponse {
  id: number;
  productId: number;
  productName: string;
  quantity: number;
  price: number;
}

export interface DeliveryResponse {
  id: number;
  orderId: string;
  postCode: string;
  street: string;
}

/** create order */
export interface CreateOrderRequest {
  userId: number;
  items: OrderItemRequest[];
  delivery: DeliveryRequest | undefined;
}

export interface OrderItemRequest {
  productId: number;
  quantity: number;
}

export interface DeliveryRequest {
  postCode: string;
  street: string;
}

export interface GetOrderByIdAndUserRequest {
  orderId: string;
  userId: number;
}

export interface GetOrdersByUserIdRequest {
  userId: number;
}

export interface UpdateOrderStatusRequest {
  orderId: string;
  userId: number;
  status: OrderStatus;
}

export const ORDER_PACKAGE_NAME = "order";

export interface OrderServiceClient {
  createOrder(request: CreateOrderRequest, metadata?: Metadata): Observable<OrderResponse>;

  getOrderByIdAndUser(request: GetOrderByIdAndUserRequest, metadata?: Metadata): Observable<OrderResponse>;

  getOrdersByUserId(request: GetOrdersByUserIdRequest, metadata?: Metadata): Observable<OrderListResponse>;

  updateOrderStatus(request: UpdateOrderStatusRequest, metadata?: Metadata): Observable<OrderResponse>;
}

export interface OrderServiceController {
  createOrder(
    request: CreateOrderRequest,
    metadata?: Metadata,
  ): Promise<OrderResponse> | Observable<OrderResponse> | OrderResponse;

  getOrderByIdAndUser(
    request: GetOrderByIdAndUserRequest,
    metadata?: Metadata,
  ): Promise<OrderResponse> | Observable<OrderResponse> | OrderResponse;

  getOrdersByUserId(
    request: GetOrdersByUserIdRequest,
    metadata?: Metadata,
  ): Promise<OrderListResponse> | Observable<OrderListResponse> | OrderListResponse;

  updateOrderStatus(
    request: UpdateOrderStatusRequest,
    metadata?: Metadata,
  ): Promise<OrderResponse> | Observable<OrderResponse> | OrderResponse;
}

export function OrderServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["createOrder", "getOrderByIdAndUser", "getOrdersByUserId", "updateOrderStatus"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("OrderService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("OrderService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const ORDER_SERVICE_NAME = "OrderService";
