apiVersion: v1
kind: Service
metadata:
  labels:
    app: order
  name: {{ .Chart.Name }}-order-cluster-ip
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 3010
      protocol: TCP
      targetPort: 3010
  selector:
    app: order
