apiVersion: v1
kind: Secret
metadata:
    name: order-secret
data:
    MYSQL_URL: {{ .Values.order.mysql_url | b64enc }}
    REDIS_URL: {{ .Values.order.redis_url | b64enc }}
    RABBITMQ_URL: {{ .Values.order.rabbitmq_url | b64enc }}
