apiVersion: apps/v1

kind: Deployment

metadata:
    name: {{ .Chart.Name }}-gateway-deployment
    labels:
        app: gateway

spec:
    replicas: {{ .Values.gateway.replicas }}
    selector:
        matchLabels:
            app: gateway
    strategy:
        type: RollingUpdate
        rollingUpdate:
            maxSurge: 1
            maxUnavailable: 1
    template:
        metadata:
            labels:
                app: gateway
        spec:
            containers:
                - image: devonyou/gateway:latest
                  name: gateway
                  envFrom:
                    - configMapRef:
                        name: gateway-config-map
                    - secretRef:
                        name: gateway-secret
                  ports:
                    - containerPort: 3000
                  livenessProbe:
                    httpGet:
                      path: "/health"
                      port: 3000
                    periodSeconds: 10
                  readinessProbe:
                    httpGet:
                      path: "/health"
                      port: 3000
                    periodSeconds: 10
