apiVersion: v1
kind: Service
metadata:
  labels:
    app: notification
  name: {{ .Chart.Name }}-notification-cluster-ip
spec:
  type: ClusterIP
  ports:
    - port: 3010
      protocol: TCP
      targetPort: 3010
  selector:
    app: notification
